# Welcome to Jekyll!
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Portfolio - Carolina Reis
email: carolina.f.reis98@gmail.com
baseurl: "/projeto" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/projeto/" # the base hostname & protocol for your site, e.g. http://example.com

# Social networks
social-username:
  linkedin: "carolina-f-reis"
  behance: "carolinareis2"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Structure
navigation:
  - title: Work
    url: /
  - title: About me
    url: /about
  - title: Contact
    url: /contact

permalink: /:title/

# Site Collections
collections:
  work:
    output: true
    permalink: work/:path


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/