# Site settings

title: Portfolio - Carolina Reis
email: carolina.f.reis98@gmail.com
baseurl: "/projeto" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/projeto/" # the base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Structure
navigation:
  - title: Work
    url: /
  - title: About me
    url: /about
  - title: Contact
    url: /contact

permalink: /:title/

# Site Collections
collections:
  work:
    output: true
    permalink: work/:path